# Generated by Django 3.2.6 on 2021-09-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_dealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dealer',
        ),
    ]
